### ISSUE TITLE
Significant whitespace breaks layout

### ISSUE THREAD

**Issue by SiAdcock** [WDOTS/wdots.github.io#121]
Not so much an issue, more like a question: how we deal with significant whitespace breaking layout?

From what I know, there are three solutions to this:

1. If whitespace breaks layout, remove whitespace between the closing tag of one element and the opening tag of the next. This is how we currently handle this scenario
2. Set `font-size: 0;` on the parent. This means we always have to override font size within the elements causing the layout to break.
3. Reduce the widths of the elements that are causing the layout to break (for instance if there are 2 elements in a row set to 50% width, reduce the width to 49%)

Happy to discuss anyone's experiences with the above or any other alternatives.

@Jameskmonger

**Comment by crgeary** [comment]
Other options:

* Flexbox
* Floats 

My thoughts..

1. Is the cleanest option, but not always realistic depending on where the content comes from. In our case it's fine because we have full control of the markup.

2. I often use the `font-size: 0` trick in cases where floats or flexbox can't be used. This is currently my preferred method for client sites.

3. I don't like this option because a space isn't 1% width, so depending on your font sizes & the width of your parent container [this will break](http://codepen.io/anon/pen/jBmprj).

**Comment by SiAdcock** [comment]
Agree with your thoughts @chrisgeary92

I reckon flexbox is the reasonable way of dealing withy significant whitespace, letting the browser / spec handle it rather than forcing a workaround.

If anyone wants to rewrite the speaker CSS using flex, that would be awesome!

**Comment by Jameskmonger** [comment]
I'll grab this @SiAdcock

**Comment by SiAdcock** [comment]
You're a beautiful man, @Jameskmonger :man_artist:

**Comment by Jameskmonger** [comment]
Solved in #127
